#!/bin/sh
#############################################################################
##
#W  zooit							 Frank Celler
#W       						     Alexander Hulpke
##
##  this shell script zoos up the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi


# clean the old files
cd ${DISTROOT}
[ -d OLD ] || mkdir OLD
rm -rf OLD/*
mv [a-z]*.zoo split OLD

if [ \! -d split ];  then
    mkdir split
fi

# remove things that should not go in the distribution

echo "Cleaning up before wrapping"
(cd $DISTROOT/$DISTNAME;

rm -rf doc/build doc/abattoir doc/Makefile alpha beta mkdistrib dev dev \
  config.*
)

# create the files that will indicate text and binary mode
echo '\!TEXT\!' > TEXTCOM
echo '/END'   >>TEXTCOM
echo '\!BINARY\!'>BINCOM
echo '/END'   >>BINCOM

# go into the source directory and create the zoo files
echo "$0: zooing version $VERSION of $DATE"

echo "README file"
cp ${DISTNAME}/etc/README .

echo "HTML Documentation (section-wise)"

for i in ${DISTNAME}/doc/htm_small/ref/*; do
  zoo ah split/html_sect$RBVERSION.zoo $i >/dev/null
  zoo c split/html_sect$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm_small/tut/*; do
  zoo ah split/html_sect$RBVERSION.zoo $i >/dev/null
  zoo c split/html_sect$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm_small/ext/*; do
  zoo ah split/html_sect$RBVERSION.zoo $i >/dev/null
  zoo c split/html_sect$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm_small/prg/*; do
  zoo ah split/html_sect$RBVERSION.zoo $i >/dev/null
  zoo c split/html_sect$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

for i in ${DISTNAME}/doc/htm_small/*.htm; do
  zoo ah split/html_sect$RBVERSION.zoo $i >/dev/null
  zoo c split/html_sect$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

rm -rf ${DISTNAME}/doc/htm_small

(cd $DISTROOT;

echo "Basic version"

for i in ${DISTNAME}/lib/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/grp/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/tst/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/pkg/example/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/pkg/example/src/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/pkg/example/doc/*; do
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

zoo ah basic$RBVERSION.zoo ${DISTNAME}/bin/gap.sh > /dev/null
zoo c basic$RBVERSION.zoo ${DISTNAME}/bin/gap.sh <TEXTCOM >&/dev/null
zoo ah split/src$RBVERSION.zoo ${DISTNAME}/bin/gap.sh > /dev/null
zoo c split/src$RBVERSION.zoo ${DISTNAME}/bin/gap.sh <TEXTCOM >&/dev/null

for i in ${DISTNAME}/doc/ref/*.tex; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/tut/*.tex; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/ext/*.tex; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/prg/*.tex; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

zoo ah basic$RBVERSION.zoo ${DISTNAME}/doc/gapmacro.tex > /dev/null
zoo c basic$RBVERSION.zoo ${DISTNAME}/doc/gapmacro.tex <TEXTCOM >&/dev/null
zoo ah basic$RBVERSION.zoo ${DISTNAME}/doc/manualindex > /dev/null
zoo c basic$RBVERSION.zoo ${DISTNAME}/doc/manualindex <TEXTCOM >&/dev/null

zoo ah split/doc$RBVERSION.zoo ${DISTNAME}/doc/gapmacro.tex > /dev/null
zoo c split/doc$RBVERSION.zoo ${DISTNAME}/doc/gapmacro.tex <TEXTCOM >&/dev/null
zoo ah split/doc$RBVERSION.zoo ${DISTNAME}/doc/manualindex > /dev/null
zoo c split/doc$RBVERSION.zoo ${DISTNAME}/doc/manualindex <TEXTCOM >&/dev/null

for i in ${DISTNAME}/doc/{ref,tut,ext,prg}/manual.six; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

# there is no README.... zoo ah basic$RBVERSION.zoo README> /dev/null

# this version will also be used for mac and pc, we don't give them the
# source however.
cp basic$RBVERSION.zoo macpc.zoo

zoo ah basic$RBVERSION.zoo INSTALL > /dev/null
zoo c basic$RBVERSION.zoo INSTALL <TEXTCOM >&/dev/null

for i in ${DISTNAME}/src/*; do
  zoo ah split/src$RBVERSION.zoo $i >/dev/null
  zoo c split/src$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/cnf/*; do
  zoo ah split/src$RBVERSION.zoo $i >/dev/null
  zoo c split/src$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

for i in  ${DISTNAME}/{Makefile.in,sysinfo.in,configure}; do
  zoo ah split/src$RBVERSION.zoo $i >/dev/null
  zoo c split/src$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah basic$RBVERSION.zoo $i >/dev/null
  zoo c basic$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

echo "Omnibus edition"
# extend the basic version
cp basic$RBVERSION.zoo gap$RBVERSION.zoo

echo "TeXed Documentation"
for i in ${DISTNAME}/doc/*/manual.dvi; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah docdvi$RBVERSION.zoo $i >/dev/null
  zoo c docdvi$RBVERSION.zoo $i <BINCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <BINCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <BINCOM >&/dev/null;
done
zoo ah split/doc$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi > /dev/null
zoo c split/doc$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi <BINCOM >&/dev/null
zoo ah docdvi$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi > /dev/null
zoo c docdvi$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi <BINCOM >&/dev/null
zoo ah macpc.zoo ${DISTNAME}/doc/fullindex.dvi > /dev/null
zoo c macpc.zoo ${DISTNAME}/doc/fullindex.dvi <BINCOM >&/dev/null
zoo ah gap$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi > /dev/null
zoo c gap$RBVERSION.zoo ${DISTNAME}/doc/fullindex.dvi <BINCOM >&/dev/null

for i in ${DISTNAME}/doc/*/manual.ps; do
  zoo ah docps$RBVERSION.zoo $i >/dev/null
  zoo c docps$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
zoo ah docps$RBVERSION.zoo ${DISTNAME}/doc/fullindex.ps > /dev/null
zoo c docps$RBVERSION.zoo ${DISTNAME}/doc/fullindex.ps <TEXTCOM >&/dev/null
zoo ah gap$RBVERSION.zoo ${DISTNAME}/doc/fullindex.ps > /dev/null
zoo c gap$RBVERSION.zoo ${DISTNAME}/doc/fullindex.ps <TEXTCOM >&/dev/null

echo "HTML Documentation"
for i in ${DISTNAME}/doc/htm/ref/*; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah html$RBVERSION.zoo $i >/dev/null
  zoo c html$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm/tut/*; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah html$RBVERSION.zoo $i >/dev/null
  zoo c html$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm/ext/*; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah html$RBVERSION.zoo $i >/dev/null
  zoo c html$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm/prg/*; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah html$RBVERSION.zoo $i >/dev/null
  zoo c html$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/doc/htm/*.htm; do
  zoo ah split/doc$RBVERSION.zoo $i >/dev/null
  zoo c split/doc$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah html$RBVERSION.zoo $i >/dev/null
  zoo c html$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

echo "Trans"
for i in ${DISTNAME}/trans/*; do
  zoo ah split/trans$RBVERSION.zoo $i >/dev/null
  zoo c split/trans$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
cp split/trans$RBVERSION.zoo gdat$RBVERSION.zoo

echo "Small"
for i in ${DISTNAME}/small/*.*; do
  zoo ah split/small$RBVERSION.zoo $i >/dev/null
  zoo c split/small$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/small/id2/*; do
  zoo ah split/small$RBVERSION.zoo $i >/dev/null
  zoo c split/small$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/small/id3/*; do
  zoo ah split/small$RBVERSION.zoo $i >/dev/null
  zoo c split/small$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/small/small2/*; do
  zoo ah split/small$RBVERSION.zoo $i >/dev/null
  zoo c split/small$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/small/small3/*; do
  zoo ah split/small$RBVERSION.zoo $i >/dev/null
  zoo c split/small$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

echo "Prim"
for i in ${DISTNAME}/prim/*.*; do
  zoo ah split/prim$RBVERSION.zoo $i >/dev/null
  zoo c split/prim$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done
for i in ${DISTNAME}/prim/cohorts/*; do
  zoo ah split/prim$RBVERSION.zoo $i >/dev/null
  zoo c split/prim$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gdat$RBVERSION.zoo $i >/dev/null
  zoo c gdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

echo "Tbl"
for i in ${DISTNAME}/tbl/*; do
  zoo ah split/tbl$RBVERSION.zoo $i >/dev/null
  zoo c split/tbl$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah tdat$RBVERSION.zoo $i >/dev/null
  zoo c tdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah macpc.zoo $i >/dev/null
  zoo c macpc.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

${BINDIR}/tommove
echo "Tom"
for i in ${DISTNAME}/tom/*; do
  zoo ah split/tom$RBVERSION.zoo $i >/dev/null
  zoo c split/tom$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah tdat$RBVERSION.zoo $i >/dev/null
  zoo c tdat$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah gap$RBVERSION.zoo $i >/dev/null
  zoo c gap$RBVERSION.zoo $i <TEXTCOM >&/dev/null;
done

echo "XTom"
mv ${DISTNAME}/tom ${DISTNAME}/tomy
mv ${DISTNAME}/tomx ${DISTNAME}/tom

for i in ${DISTNAME}/tom/*; do
  zoo ah split/tom$RBVERSION.zoo $i >/dev/null
  zoo c split/tom$RBVERSION.zoo $i <TEXTCOM >&/dev/null
  zoo ah xtom$RBVERSION.zoo $i >/dev/null
  zoo c xtom$RBVERSION.zoo $i <TEXTCOM >&/dev/null
done

echo "------------------------------"

echo "Lib"
for i in ${DISTNAME}/lib/*; do
  zoo ah split/lib$RBVERSION.zoo $i >/dev/null
  zoo c split/lib$RBVERSION.zoo $i <TEXTCOM >&/dev/null
done

echo "Tst"
for i in ${DISTNAME}/tst/*; do
  zoo ah split/tst$RBVERSION.zoo $i >/dev/null
  zoo c split/tst$RBVERSION.zoo $i <TEXTCOM >&/dev/null
done

echo "Grp"
for i in ${DISTNAME}/grp/*; do
  zoo ah split/grp$RBVERSION.zoo $i >/dev/null
  zoo c split/grp$RBVERSION.zoo $i <TEXTCOM >&/dev/null
done

echo "------------------------------"
echo "Linux binaries"
zoo ah gap$RBVERSION-i686-unknown-linux2.0.31-gcc.zoo ${DISTNAME}/${LINUXPATH}/gap >/dev/null
zoo c gap$RBVERSION-i686-unknown-linux2.0.31-gcc.zoo ${DISTNAME}/${LINUXPATH}/gap <BINCOM >&/dev/null
zoo ah gap$RBVERSION-i686-unknown-linux2.0.31-gcc.zoo ${DISTNAME}/${LINUXPATH}/gac >/dev/null
zoo c gap$RBVERSION-i686-unknown-linux2.0.31-gcc.zoo ${DISTNAME}/${LINUXPATH}/gac <BINCOM >&/dev/null

echo "Pc version"
cp macpc.zoo gappc$RBVERSION.zoo

cp ${DISTNAME}/bin/i686-unknown-linux2.0.31-gnuwin32gcc/gap ${DISTNAME}/bin/gapw95.exe
cp /usr/gnuwin32/i586-pc-cygwin32/lib/cygwin.dll ${DISTNAME}/bin
zoo ah gappc$RBVERSION.zoo ${DISTNAME}/bin/gapw95.exe> /dev/null
zoo c gappc$RBVERSION.zoo ${DISTNAME}/bin/gapw95.exe <BINCOM >&/dev/null
zoo ah gappc$RBVERSION.zoo ${DISTNAME}/bin/cygwin.dll> /dev/null
zoo c gappc$RBVERSION.zoo ${DISTNAME}/bin/cygwin.dll <BINCOM >&/dev/null
zoo ah gappc$RBVERSION.zoo ${DISTNAME}/bin/gap.bat> /dev/null
zoo c gappc$RBVERSION.zoo ${DISTNAME}/bin/gap.bat <TEXTCOM >&/dev/null
zoo ah gappc$RBVERSION.zoo INSTALL.WIN > /dev/null
zoo c gappc$RBVERSION.zoo INSTALL.WIN <TEXTCOM >&/dev/null
rm ${DISTNAME}/bin/{gapw95.exe,cygwin.dll}

echo "Mac version"
mv macpc.zoo gapmac$RBVERSION.zoo
zoo ah gapmac$RBVERSION.zoo INSTALL.MAC > /dev/null
zoo c gapmac$RBVERSION.zoo INSTALL.MAC <TEXTCOM >&/dev/null

echo "Mac src"
find ${DISTNAME}/{macsrc,macgac} -print | zoo ahI macsrc$RBVERSION.zoo > /dev/null

)

exit 0
