#!/bin/sh
#W  make_doc						     Alexander Hulpke
##  this shell script TeXs the documentation 
##
echo "TeXing documentation"
# build the ref. manual
(cd build;make)

# tex all manuals and build their biliography and index information
(cd ext; tex manual;bibtex manual;tex manual;../manualindex manual)
(cd prg; tex manual;bibtex manual;tex manual;../manualindex manual)
(cd ref; tex manual;bibtex manual;tex manual;../manualindex manual)
(cd tut; tex manual;bibtex manual;tex manual;../manualindex manual)
# finally tex all manuals again to get cross-references right
(cd ref; tex manual; dvips -D300 manual)
(cd tut; tex manual; dvips -D300 manual)
(cd ext; tex manual; dvips -D300 manual)
(cd prg; tex manual; dvips -D300 manual)

# make the comprehensive index
./allmanualsindex
tex fullindex
dvips -D300 fullindex

# The HTML versions
cd htm
echo "HTML documentation"
make
